XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXX
        X X
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXX X
            XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX XX X
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX XXXXX X
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX XXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX
        X

        XXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXXXX XXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXX XX X
            XXXXXXXXXXX XXXXX
            XXXXXXX XX
            XXXXXXXX XX
        X

        XXXXXXXXXXXXXXX XX X
            XXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XX
        X

        XXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX XXXX XXXXX
        X

        XXXXXXXXXX XXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX X XXX XXX XX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XX
        X

        XXXXXXXXXXXXXX XXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
        X

        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXX X
                XXXXXXXX XXXX XXXXX
                XXXXXXX XXXXX
            X

            XXXXXXXXXXXXX XX X
                XXXXXXXXXX XXXXX
            X
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXX
        XXXXXX

        BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
                        BBB BBBBB BB BBBBBB
                            XXXXXXXXX
                        BBBBBB
                    BBBBBB
                XXXXX
            XXXXXX
        BBBBB

        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX
                
            XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                X XXXXXX XX XXXXXX
            XXXXXXXXX
        XXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX X XXXXXXXXX X XXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXX XX XXXXX XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXX XXXXXX XX XXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX