BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    
    XXXX XXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    
    XXXX XXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
    
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
    XXXXXXX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXX XXXXXXX
        X
        XXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXX XXXXXXX
            XXXXXXX XXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          

            XXXX XXXXXXX X XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX 
                               XXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                        BBB BBBBBB BBBBB BB BBBBBBBBBBBBBB
                            XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                                
                            XXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXX XX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                            XXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXX XXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                        XXXXXXXX
                        XXXXXXX
                            BBB BBBBBBB BB BBBBBBBB
                            XXXX
                                XXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBBBBBBBBB
                                                XXXX XXXXXX XXXXXXX
                                            BBBB
                                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXXFFFFFFFFFFXXXXXXX
                                                XXXXXX
                                            BBBBB
                                        XXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBB
                                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BBBBB
                                        XXXXXX
                                    XXXXXX
                                XXXXX
                                XXXX
                                    BB BBBBBBBBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBB BBBBBBBBBBBBBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBBB
                                XXXXX
                                XXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        BBBBBB
                                        BB BBBBBBBBBBBBBBBBBBBBBBBBB B B
                                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXX
                                        BBBBB
                                    XXXXXX
                                XXXXX
                                XXXX
                                    BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBB BBBBBBBBBBBBBB BB BBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBB BBBBBBBBBBBBBB BB BBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBBB
                                    BB BBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBB
                                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBBB
                                XXXXX
                                XXXXFFFFFFFFFFFFXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX 
                                           XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXX
                                        XXXX
                                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XFFFFFFFFXXX
                                                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXX
                                        XXXXXXXXX
                                    XXXXXX
                                XXXXX
                            XXXXX
                            BBBBBB
                            XXXXXXXX
                        XXXXXXXX
                BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                        
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                BBBBB
            XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXX XX XXXXXXXXXXX XX XXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXX XXXXXXX X XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXX XXXX XXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX

BBBBBBBBBB
XXXXXXXX
XXX XXXXXXXXXXXXXXX X XXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXX X XXXXX
    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXX
            X
        X
    X
    XXXXXX XXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX
        XX
        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
        XXXXXXXXXX XX X
            XX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXX XX XXXXXXX XXXXXXXX X X XXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXX
            X
        XX
        XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XX XXXXXXX XXXXXXXXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
XXX
XXXXXXXXX
XXXXXXX
XXXXXXX