BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB X  gettext(u'Detalhes do Projeto') BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
XX XXXXX XXXXXXXXXX XX
XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXX
X

XXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX XX XXXXXXXXX
X

XXXXXXXXXX XXXXXXX X
    XXX XXXX X XXXXXXXX XXXX X
    XXX X XXXXXXXX XX X
X

XX XXXX XXXXX XXXXXX XX
XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
X

XX XXXX XXXXXXX XXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXX
X

XXXXXXXXXX XXXXXXXXXXXX X
    XXX XXXX X XXXXXXXXXXXX X X XXX XXXXXXXXX XXXX XXXX XXXXX X
    XXX X XXXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX X
X

XX XXXX XXXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXX XX
X

XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXX X XXXXX
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXX
X

XX XXXXX XXXXXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXX XXXX XX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXX X XXXXX
X

XXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
X

XX XXXXXXX XXXXXX XXXX XX
XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXX XXXX XX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXX XXX X
    XXXXXX XXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXX XXX X
    XXXXXXXXXX XXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
X

XX XXXXXXXX XXXXXXX XX
XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XX XXXXXXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXX
    X
X

XX XXXXXXXXXX XX
XXXXXXXX X
    XXXXXXXXXX XXXXXX XXXX XXXXXXXXX
X

XXXXXXXXX X
    XXXXXXXXXX XXXXXXX XX XXXXXXXXX
X

XXXXXXXXXX XXXXXX X
    XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
X

XXXXXXXXXX XXXXXXX X
    XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXXXX X
    XXXXX XXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXX XXXXXX
X

XX XXXXXXXXXXXXX XXXXXX XXXX XXXX XXXXX XX
XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX X X
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXX XXXXX
    XXXXXXX XXXX XX
X

XXXXXXXXXXXXXXXXXXXXXX XXX XXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XX
    XXXXXX XXXXXXXX
    XXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXXX XXXX XX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XX
X

XX XXXX XXXXXXX XXXXXX XX
XXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXX
X

XXXXXXXXXX XXXXXXXXXXXXXX X
    XXX XXXX XXXX X XXXXXXXX XX X
    XXXX XXXX XXX X XXXXXXXX XXXX X
    XXXX XXX X XXXXXXXX XX X
X

XX XXXXXX XXXXX XXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXX XXX XXX XXXXXXXX XXX XXX XXXXX
X

XX XXXXXX XXXXXX XX
XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX XXX XXX XXX XXXXXXXX XXX XXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXX XXX XXXXXXXX XXX XXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
X

XX XXXXXXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXX X
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX XXXXXXX
    X
X

XX XXXXXXXXX XXXXXXX XX
XXXXXXXX X
    XXXXXXXXXX XXXXXX XXXX XXXXXXXXX
X

XXXXXXXXX X
    XXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXX X
    XXXX X
        XXXXXXXX XX
    X
    XX X
        XXXXXXXX XX
    X
X

XXXXXXXXXX XXXXXXX X
    XXXX X
        XXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    XX X
        XXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXXXXX
    X
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBB
                XX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXX
            BBBBB
            
            XXXX XXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Acesse o site') 
                    XXXX
                BBBBB
                
                BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Ver repositório') 
                    XXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                    BB BBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX
                    BBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXX
                    BBBB BBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXX
                    BBBBXXXXXXXXXXX XXXXXXXXXXBBBBBXX
                    
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Trading Volume') XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Floor Price') XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Items') XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Owners') XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXX XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXX XXXXXXX XXXX XXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                         gettext(u'Collection') 
                    XXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            BBB BBBBBB BB BBBBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFXXXX
                                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFFFFXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFXXXXX
                                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFF FFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFXXXX
                                    XXXXXX
                                XXXXXX
                            BBBBBB
                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Nenhuma imagem disponível') XXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    BBBBB
                XXXXXX
                
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXX XXXXXXXX XXX
BB BBBBBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                 gettext(u'Projetos Relacionados') 
            XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Outros projetos que podem interessar') 
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXX XXXXX XXX
                    XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXX 
                                 XXXXXX 
                                 XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXX
                        BBBBB
                        
                        XXXX XXXXXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX
                                BBBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXX
                                BBBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXX
                                BBBBXXXXXXXXXXX XXXXXXXXXXBBBBBXX
                                
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXX XXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            
                        XXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                                
                            XXXX
                        BBBBB
                        
                        XXXX XXXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    BB BBBBBBBBBB
                                        XX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                    BBBBB
                                    
                                XXXXXXX
                            BBBBBB
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
                                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XFFFFFFFF
                                XXXXXXX
                            BBBBB
                        XXXXXX
                        
                        XXXX XXXXXX XXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX 
                               XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                                 gettext(u'Ver Detalhes') 
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBB

XXXX XXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
    XXXXXX
XXXXXX

BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
XX XXXXXXX XXXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXX X XX
XXX XXXXXXXXXXXXX X XXX

XX XXXXXXXXXX XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X
            XXXX XXXXXXXX
            XXXX XXXXXXX
        XX
    XXX
    
    XX XXX XXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX X X
        XXXXXXXXXX XXXX
        XXXXXXXXXXX XXXX XXX XXXXX XXXX
    XX
    
    XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
            X
        XXX
    XX XXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXX XXXXXXXXX XXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXX
    XXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX X
        XXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXX X XXXX
        
        XX XXXXXX XXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXXXX XXXXX XXX XXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXX XXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXX X XXXX
    XXXXXXXXXXXXXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXX XXXXXXX XXXXX XXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXX XXXXX
    
    XX XXXXXXX XXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXX XXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXX
    
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXX
    
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXX
X

XX XXXXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    
    XXXXXXXXXXXXX X
        XXXX XXXXXXXXX
            XXXXXXXXXXXXX
            XXXXXX
        XXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXX
        XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX
            XXXXXX
    X
XXX

XX XXXXXXXXXXX XXXXXXX XXX XXXXXX
XXX XXXXXXXXXXX X XX
XXX XXXXXXXXX X XX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXX
    XXXXX XXXX X XXXXXXXXXXX X XXXXXXXXXX
    
    XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X
        XX XXXXX X XX X
            XXXXXXXXXXXX XX XXXXX XXXX X XXXX XXXXX
        X XXXX X
            XXXXXXXXXXXXXXXX XX XXXXX XXXXX X XXXXXXXX XXXXX
        X
    X
X
XXXXXXXXX
BBBBBBBB