BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    
    XXXX XXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    
    XXXX XXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
    
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
    
    XXXXXXX
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
    X
    XXXXXXXXXX X
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXX XX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXX
    X
    XXXXXXXXXX XXXXXXXXXXXXX X XXXX X
        XXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXX X X X XXX XXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXX
        XXXX XX
        XXXXXXXX XXX
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX X X XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXX XXXXX
        XXXXXXXX XXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX XX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXX XX
    X
    XXXXXXXXXXXX X
        XXXXXXXXX XXXXXXX
        XXXX XX
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
        XXXX XXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXX
                XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXX XXXXXX XXXXXXXXXX
                    XXX XXXXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX
                XXXX
            XXXXXX
        XXXXXX

        XXXX XXXXX XX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    XXXX XXXXXXXXXXX XXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX 
                                       XXXXXXXXXXXXXXXX XXXXXXX XX XXXXXX XX XXXXXXX XXX XXXXXX XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX 
                                       XXXXXXXXXXXXXXX XXXXXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXX XXXXXXX X XXXX XXXXX X XXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                            
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX 
                                       XXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXX XXX XXXXXX X XXXXXX XXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXX 
                                       XXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XX XXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXX XXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX 
                                      XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXXXXXXXXX XXXX XXXXXXXXXXX X XXXXXXXX XX XXXXXX XX XXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXX XXXXXXXXXX XX XXX X XXXXXXXXXX XXX XXXX XX XXXXXXXXXXXXX 
                                      XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXX X XXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXX X XXXXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXX XXXXX XX XXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                            
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX 
                                       XXXXXXXXXXXXXXX XX XXXXX XXXXXXX XXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXX XX X XXXXXXXXX X X XXXXXXXX XXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                            
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXXX
                                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXX X XXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXX XX XXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX 
                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XX XXXXX XXXXXXXXXXX XXXX X XXXXXX XXXX XXXXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                            
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
                                XXXXXXXX
                                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX 
                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXX XXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX
                                BBBBB
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXX
                                    BBB BBBB BB BBBBBBBBBBBBBBBB
                                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXFFFFFXX
                                            
                                            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                                        XXXXXXXX
                                    BBBBBB
                                XXXXXX
                            XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXX XXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXX XXXXX XXXXXXXXXXX
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                
                                XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                                    XXXXXXXXXXXX XXXXXXXXX XX XXXXXXXX
                                XXXXXX
                            XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXX
                            BBBBB
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                                    XXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXX XX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XX XXXX
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXBBBBXXXXX XXXXXXXBBBBBXXXXXXX
                            XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                                XXXXXX XXXXXXXX
                            XXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXXXX
                                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                                XXXXXXXX
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXXX
        XXXXXX

        XXXX XXXXX XXXXXXXXX XX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXX XX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXX
                XX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXX
            XXXXX
            XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX XX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
                        
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXX XXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                                XXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXX
                            XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXX XXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
                            XXXXX XXX XX XXXXXX XXXXX X XXXXXXXXXXXXXXX
                            XXXXX XXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXXXX XX XXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXX XX XXXXXXXXXX
    XXXXX XXXXXXXXXXXX X X
        XXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXX XX
        XXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXX XX
        XXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX X
    XX
    
    XX XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XX XXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXX XXXXXXX XX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XX XXXXXXX X XXX X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                XX XXXXXXX X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                
                XXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XX XXXXXXXXXXX
        X
    XXX
    
    XX XXXXX XX XXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXX XX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            XXX
        XXX
    X
    
    XX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXX XX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXX
    XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
    
    XX XXXXXXX XX XXXXXXXXX XX XXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX X
        XXX XXXXXXXX X XX
        XXX XXXXXXXXXXX X XX
        
        XX XXXXXX XXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXX XX XX
        XX XXXXXXXX XXXXXXXX XX XXX
        XX XXXXXXXXXXX XXXXXXXX XX XXX
        
        XX XXXXXX XXXXXXXXX XXX XXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXX XX XX
        XX XXXXXXXXXXX XXXXXXXX XX XX
        XX XXXXXXXX XXXXXXXX XX XX
        XX XXXXXXXXXX XXXXXXXX XX XXX
        XX XXXXXXXXXXXX XXXXXXXX XX XXX
        XX XXXXXXXXXXXXXX X XX XXXXXXXX XX XXX
        XX XXXXXXX X XX XXXXXXXX XX XXX
        
        XX XXXXXXXXX XXXXX XX XXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
        XX XXXXXXXXX X XXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X
    
    XX XXXXXXX XX XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXX XXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXX X
                XX XXXXXXX XXXXXXX XX XXXXXXX XXXXX
                XX XXXXXXXXXX X X X XXXX X XXXXX X
                    XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXX
                    XXXXXXXXXX X XXX
                    XXXXXXX
                X
                
                XX XXXXXXX XXXX XX XXXXXXX
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXX XX XXXXXXX XXXXXXXXX XXX XXXX XXX XX XXXXXXXX
                    XXXXXXXXXX X XXX
                    XXXXXXX
                X
                
                XXXXX XXXXXX X XXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXXXXXXX X
                    XX XXXXXX XXXXXXX XXXXXXXX XX XXXXXXX
                    XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                    
                    XX XXXX XXXX XXXXXXX
                    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX X XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXX
                    XXXXXXXXXXXXXXXXX X X
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX
                    
                    XX XXXXXXXX XXXX X XXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXX
        XXX
    X
    
    XX XXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
            XXXX
            
            XX XXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXX X XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX
        XXX
    X
    
    XX XXXXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXX X
            XXX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX X XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX
                
                XX XX XXXXXXXX XX XXX XXXXX XX XX XXXXX
                XX XXXXXXXXX X XX X XX X XX X XXXXX X
                    XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                            XX XXXX XXX XXXXXXXXXXXX X
                                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXX XX XXXXXXXXXX X
                                    XXXXXXXXXXX X XXXXXXXXXX
                                X
                            X
                        XXX
                        XXXXXXXXXXXXXXXXX
                    X
                X
            X XXXXX XXX X
                XXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXX XXX
            X
        X
    X
    
    XX XXXXXXXXX XX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        X
        
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        X
        
        XX XXXXXXXX XXXXXX XX XXXXX
        XXXXXXXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
    
    XX XXXXXXXXX XXXXXXXXX XXXX XXXXX XX XXXXXX XXXX XXXXXXXXX XXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXX
    
    XX XXXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
XXX

XX XXXXXXX XX XXXXX XX XXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXX XXXXX XX XXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XX
        XXXXXXXXXXXX XX XXXXXX
    
    XX XXXXXXXXX XXXXXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    
    XX XXXXXX XXX XXXXX X XXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X X
        XXXXXXXXXXXXXXXXXX X XXXXX XX XX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XX
        XXXXXXXXXXXX X XXXXX XX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXX X XXXXX XX XX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XX
        XXXXXXXXXX X XXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX X
    XX
    
    XX XXXXXXX XX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXX
    X
    
    XX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXX
    XX XXXXXXXXXXXXXXXXXXXXX X XX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        XX XXXXXXXXXXXXXXXXXXXXX X XX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXX XX XXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
    
    XX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
    
    XX XXXXXXX XX XXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXX X XXX XXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXXXX XXXXXXXXXXX XX XXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XX XXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX X XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXX XX X XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX XXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX XXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XX XXXXXXX XX XXXXXXXXXX X XX XXXXXX XXXXXXXXXXXX
X

XX XXXXXX XXXXX XX XXXXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXX
    X
XXX

XX XXXXXX XXXXX XXX XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXX XXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX
    X
XXX
XXXXXXXXX
XXXXXXX
XXXXXXX