BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB X XXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXX XXXXXXX XXX


XXXX XXXXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        
        XXXX XXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                        
                    XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        
                    XXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXXXXX XX XXXXXXX
                    XXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX X X XXXX XXXXX X X XXXXXXXX XXXXXXXXX
                                XXXXX XXXXXX XXXXXXXX XXXXXXXXXX X X XXX XXXXXX X X XXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXX XXX X X XXXXXXXXXXXXX X X XXXXXXXXXXXXXX XXXXXXX X X XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXX X X XXXX XXXXXXXXX XX X XXXXX X XXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX X X XXXXX XXXXXX XXXXXXXXXXXXXXXXX X X XXXXXXXXXXX XXXX X X XXXXX X X X XXX XXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXX XXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                BBB BBBBB BB BBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXX XXXXXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                        XXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                
                            XXXXX
                            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                
                            XXXX
                        XXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXX
                            
                        XXXXXXX
                    XXXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        
                    XXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXXXX XXXXXXXXX
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX
                            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                                
                            XXXXX
                            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                
                            XXXX
                        XXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXX
                            
                        XXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXX XX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXX X X XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX X X XXXXXXX XXX XXXXXXXXXX X X XXX XXXXXXXXXXXXXXXXXXXXX X X XXXXXXX XXXXXXXX XXX X X XXXXXXXX XXXXXXXX X X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXX XXXXXXXXX XX XXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB