BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB X  gettext(u'Meu Portfólio') BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Sobre Mim') 
                XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                     gettext(u'Sou um desenvolvedor apaixonado por criar soluções inovadoras e eficientes. Com experiência em desenvolvimento web full-stack, sempre busco aprender novas tecnologias e aplicar as melhores práticas em meus projetos.') 
                XXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                     gettext(u'Especializado em Python, Django, JavaScript e tecnologias modernas de desenvolvimento web. Adoro trabalhar em equipe e contribuir para projetos que fazem a diferença.') 
                XXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                            XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                    XXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                            XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXX X XXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X XXXXXXXXX XXXXX XXXXX X XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X X XXXX X XXXXXXXXXXXXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXX XX XX XXXXXX XX XXXXXXXXXXXXXXX XXXX XXXX X XXXXXX XXXXXXXXXX
                        XXXXXX
                    XXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                            XXXXX XXXXXX XXXXXXXX XXXX XXXXXXXX XX X XXXXX XXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Foto de perfil') X XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                 gettext(u'Tecnologias') 
            XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXX XXXXXXX XX XXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXX
                     XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXX
             XXXXXX
             XXXX XXXXXXXXXXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXX
                     XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXX
             XXXXXX
             XXXX XXXXXXXXXXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXX
                     XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXX
             XXXXXX
             XXXX XXXXXXXXXXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXX
                     XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXX
             XXXXXX
             XXXX XXXXXXXXXXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXX
                     XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXX
             XXXXXX
         XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXX XXXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                 gettext(u'Projetos em Destaque') 
            XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'Alguns dos meus trabalhos mais recentes') 
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX X XXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Projeto 1') X XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                         gettext(u'Sistema de Gestão') 
                    XXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                         gettext(u'Sistema completo de gestão empresarial desenvolvido em Django.') 
                    XXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Ver mais')  X
                    XXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXX X XXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Projeto 2') X XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                         gettext(u'E-commerce') 
                    XXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                         gettext(u'Plataforma de e-commerce com carrinho de compras e pagamento online.') 
                    XXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Ver mais')  X
                    XXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXX X XXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Projeto 3') X XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                         gettext(u'API REST') 
                    XXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                         gettext(u'API REST completa com autenticação JWT e documentação.') 
                    XXXX
                    XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Ver mais')  X
                    XXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Ver Todos os Projetos') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
             gettext(u'Vamos Trabalhar Juntos?') 
        XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
             gettext(u'Estou sempre aberto a novos projetos e oportunidades interessantes.') 
        XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Entre em Contato') 
        XXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB