BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBXXXXX X XXXXXX XXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXX XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XX
    XXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
X

XXXXX XXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXX XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXXXXXX
X

XXXXX XXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXX XXXXXX
X

XXXXX XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X X X XXX XXXXXXXX XXXX XXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    XXXXXX XXXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
X

XXXXX XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXX XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX XX X
    XXXXXXX XX
    XXXXXXXXXXXXX XXXXX
X

XXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXX XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX
X

XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXX XXXX XXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
    X
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXX
        
        BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
                        BBB BBBBB BB BBBBBB
                            XXXXXXXXX
                        BBBBBB
                    BBBBBB
                XXXXX
            XXXXXX
        BBBBB
        
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                    X XXXXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXX 
                       XXXXXXX 
                       XXXXX
                       XXXXXXXXXXXXXXXXXX 
                       XXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
                       XXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                    X XXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX 
                       XXXXXXX 
                       XXXXX
                       XXXXXXXXXXXXXXXXXX 
                       XXXXXXXXXXXXXXXXXXX XXX XXXXXX
                       XXXXXXXXX
            XXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                X XXXXXX XX XXXXXX
            XXXXXXXXX
        XXXXXXX
        
        XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
            X XXXXXX XX XXXXXX
        XXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX X XXXXXXXXX X XXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXX XX XXXXX XXX XXXXXXXXXXX XXXX XXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB