# Generated by Django 5.1.6 on 2025-07-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='blog/imagens/', verbose_name='Imagem de Destaque'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='resumo',
            field=models.TextField(blank=True, help_text='Resumo do artigo (máximo 300 caracteres)', max_length=300),
        ),
        migrations.AddField(
            model_name='artigo',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
