# Generated by Django 5.2.4 on 2025-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('tecnologias', models.CharField(help_text='Ex: Python, Django, React', max_length=200)),
                ('link_repositorio', models.URLField(blank=True, null=True)),
                ('link_deploy', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Marque para exibir o projeto no site.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
