# Generated by Django 5.2.4 on 2025-07-20 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: fab fa-python)', max_length=100)),
                ('cor', models.CharField(default='#000000', help_text='Cor em hexadecimal', max_length=7)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem de Programação'), ('framework', 'Framework'), ('biblioteca', 'Biblioteca'), ('banco', 'Banco de Dados'), ('ferramenta', 'Ferramenta'), ('outros', 'Outros')], default='outros', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-destaque', 'ordem', '-data_criacao'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_completa',
            field=models.TextField(blank=True, verbose_name='Descrição Completa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_curta',
            field=models.TextField(blank=True, help_text='Resumo do projeto (máx. 300 caracteres)', max_length=300, verbose_name='Descrição Curta'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para exibir na página inicial', verbose_name='Projeto em Destaque'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição (0 = primeiro)', verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('desenvolvimento', 'Em Desenvolvimento'), ('concluido', 'Concluído'), ('pausado', 'Pausado'), ('arquivado', 'Arquivado')], default='desenvolvimento', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Marque para exibir o projeto no site', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_deploy',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Deploy/Demo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_repositorio',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Repositório'),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens dos Projetos',
                'ordering': ['ordem', 'data_upload'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='portfolio.tecnologia', verbose_name='Tecnologias'),
        ),
    ]
