# Generated by Django 5.2.4 on 2025-07-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tecnologia_alter_projeto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_inicio',
        ),
    ]
