BBBB BBBBBB
XXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XX XXXXXX XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX

        XXX XXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXX
            XXXX
                XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XX XXXX XXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXX
                XXXX
            XXXXX
        XXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXXXXX