BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBB BB BBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBB gettext(u'Meu Portfólio') BBBBBBBBXXXXXXXX
    
    XXXX XXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    
    XXXX XXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XXXX XXXXXXXX XXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXX XXX XXX
    XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
                XXXX XXXX X XXXXXXXX XXX
                XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXX XXXX
                XXXX
                
                XXXX XXXX X XXXXXXXX XXXXXXXX X XXXXXXX XXX
                XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBXXXXXXXXXXBBBBBXX gettext(u'Início') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXX gettext(u'Projetos') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXX gettext(u'Artigos') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXX gettext(u'Currículo') XXXX

                    
                    XXXX XXXXXXXX XXXXXXXX XXXXXXX XXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBXXXXXXXXXBBBBBXX
                            XX
                        XXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXXBBBBBXX
                            XX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXX XXXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXX XXXX XXXXXXXXXXX
                        XXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBXXXXXXXXXXBBBBBXX gettext(u'Início') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXX gettext(u'Projetos') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXX gettext(u'Artigos') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXX gettext(u'Currículo') XXXX
                
                XXXX XXXXXXXX XXXXXXXX XXXXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBXXXXXXXXXBBBBBXX
                        XX
                    XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXXBBBBBXX
                        XX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        BBBBB BBBBBBB
        BBBBBBBB
    XXXXXXX
    
    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXX XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXX XXXX  gettext(u'Meu Portfólio') X  gettext(u'Todos os direitos reservados') XXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX
    
    XXXX XXXXXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
    
    XXXXXXXX
    XX XXXXXX XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
            
            XX XXXXX XXXXXX XXXX XXXX XXXXXXXX XX X XXXX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            XXX
        X
    XXX
    
    XX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXX X XBBB BBBBBBBBBBBBBBXX
        
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X XXX
        
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXX X XXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
    X
    
    XX XXXXX XXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXX X XXXX
            XXX
        X
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXX
        X
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXX X XXXX
            XXX
        X
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXX
        X
    XXX
    
    XX XXXXXXXX XXXXXXXXX XXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX X X
        XXXXXXXXXX XXXXXXXXXXXXX X
            XX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
            XXX X XXXXXXXXXXXXXXXXXXXX XXXX XXXX X
            XXXX X XXXXXXXXXXXXXXXXXXXX XX XXXX X
        X
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXX XXXX
    XXXXXXXX XXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX X
            XX XXXXXX XXXXXXX XXXXXXX XXX XXX XXX XXX XXXXXX XXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            
            XX XXXXXX XXXXXXXX XXXXXXX XXX XXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXX X XXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
    X
    
    XX XXXXX XXX XXXXXX XXXXXXXX XXXXX XXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXX XXXXX X XXXXXXX
    XXX
    XXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX