BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XX XXXXXXXX
                XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXX
            XXXXXX



            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXX XXXXXX X XXXXXXXXX XXXX XXXXXXXX XX XXXXX XXXXXXXXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXX X XXXXXXXX XXXXXXX XX XXXX XXX XXXXXXXXXXXXXX
                XXXX
                XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    XXXXXXX XXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXX X XXXX XXXXXXX XXXX XX XXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX