BBBB BBBBBB BBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    BBBBBBBBBBBB
XXXXXXX

XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXXX XXXXXXX XXXXXXXX
        XXXXXX
    XXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXXXX
    XXXXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX
